### ISSUE TITLE
This module suddenly stopped working the other day.

### ISSUE THREAD

**Issue by mishmanPi** [thess/MMM-MktIndex#2]
This module has been working fine up unitl a few days ago. Now all that is displayed in the stocks I follow are dashes and no update timestamp is listed. Is it possible the url has changes for the yahoo stocks page used in the module?

**Comment by thess** [comment]
All I can say at-the-moment is that the MktIndex is working here. If you could check any MM logs available (I use pm2 - log is located in: `~/.pm2/logs/MagicMirror-error.log`) to see where things are failing for you.

Apparently, Yahoo has changed the access to their API/site and you may be affected by it. See discussions here:

https://github.com/gadicc/node-yahoo-finance2/issues/764
https://www.npmjs.com/package/yahoo-finance2

I don't know why my installation has been working -- perhaps due to no software updates done since things have been running OK with yahoo-finance2 v2.4.2. I don't know if there is anything I can do.

**Comment by thess** [comment]
I upgraded the yahoo-finance2 dependency to the latest (v2.11.2). See if that fixes your issue.

**Comment by mishmanPi** [comment]
Ted, I swapped out the package.json file with your updated version and the Stock data is still not displaying,

**Comment by thess** [comment]
Need some logging info... If you set `debug: true`, in your config.js for the MMM-MktIndex module, you will get some additional output.

Also, after copying the `package.json` file, did you execute `$ npm install` to update module?

**Comment by mishmanPi** [comment]
I forgot to update the module and after doing that it works now.
Thank you very much for the prompt fix to your awesome module.
